server:
  #服务端口
  port: ${PORT:50101}
spring:
  application:
    name: onlineEducation-govern-center #onlineEducation-govern-center #指定服务名
eureka:
  client:
    # 服务注册，是否将自己注册到Eureka服务中
    registerWithEureka: true
    #服务发现，是否从Eureka中获取注册信息
    fetchRegistry: true
    #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果不配置则默认本机8761端口）
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://eureka02:50102/eureka/}
  server:
    enable-self-preservation: false #是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: ${EUREKA_DOMAIN:eureka01}

