server:
 port: 31000
spring:
  application:
    name: onlineEducation-cms-client
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017
      database: oe_cms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
onlineEducation:
  mq:
  #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_cms_postpage
    routingKey: 5a751fab6abb5044e0d19ea1 #此routingKey为门户站点ID

logging:
  config: classpath:logback-spring.xml